version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install -g aws-cdk
      - python -m venv .venv
      - .venv/bin/pip install -r requirements.txt

  build:
    commands:
      - echo "Synthesizing CDK app..."
      - cdk synth
      - echo "Deploying AI Healthcheck stack..."
      - cd 02_ai_healthcheck_bedrock
      - cdk deploy --require-approval never

artifacts:
  files:
    - "**/*"
