version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.11
        nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install -g aws-cdk
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Synthesizing CDK app..."
      - cd 03_bedrock_container
      - cdk synth
      - echo "Deploying Bedrock Container stack..."
      - cdk deploy --require-approval never

artifacts:
  files:
    - "**/*"

